version: '3.8'

services:
  db:
    container_name: postgresql_db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  test_db:
    container_name: postgresql_test_db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "6000:5432"
    volumes:
      - test_database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      --url="jdbc:postgresql://db:5432/${DB_NAME}"
      --username=${POSTGRES_USER}
      --password=${POSTGRES_PASSWORD}
      --searchPath=/liquibase/changelog
      --changeLogFile=changelog.xml
      update
    volumes:
      - ../app/migrations:/liquibase/changelog

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  backend:
    container_name: backend
    build:
      context: ../app/
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  tests:
    container_name: tests
    build:
      context: ../app/
      dockerfile: Dockerfile.tests
    depends_on:
      - backend
    command: ["pytest", "-v", "tests"]
    env_file:
      - ./.env

volumes:
  database:
  test_database:
